before:
  hooks:
    - go mod tidy

builds:
  - binary: yts
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/conormkelly/yts-cli/cmd.version={{.Version}}
      - -X github.com/conormkelly/yts-cli/cmd.commit={{.Commit}}
      - -X github.com/conormkelly/yts-cli/cmd.buildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      yts_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
